### PR TITLE
Switch to distro module for extra compatibility, actually output kern…

### PR DESCRIPTION
**Pull request by Sophon96**
…el version under kernel rather than just the platform

### CODE REVIEW

**Comment by mugman174** [comment]
What if someone doesn't have the `distro` module

**Comment by mugman174** [comment]
Also https://git.genericlinux.org/Generic-Linux/Genfetch

**Review by mugman174 — CHANGES_REQUESTED** [review]
Don't use the Distro module because it's just another module that people'll need to install, and this needs to be more generic.

**Comment by mugman174** [comment]
> Your opinion doesn't matter to me

**Comment by mugman174** [comment]
jk jk

**Review by mugman174 — APPROVED** [review]
ehh it works

**Comment by Sophon96** [comment]
*Technically*, this is the proper way to find the distro in Python

**Comment by mugman174** [comment]
You realize that you/I could merge this PR right now?

**Comment by Sophon96** [comment]
Not all distros have a os-release file

**Comment by Sophon96** [comment]
> You realize that you/I could merge this PR right now?

Yes

**Review by videotoaster — COMMENTED** [review]
good ig

**Comment by mugman174** [comment]
> Not all distros have a os-release file

*Alpine Linux*

**Pull request merged**
